name: SeekDB Farm2

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  seekdb:
    name: seekdb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
      - name: action by seekdb
        uses: ./.github/script/
        id: seekdb
        with:
          pipeline_id: ${{ github.run_id }}
          project: ${{ github.repository }}